### PR TITLE
Add swagger

### PR DESCRIPTION
**Pull request by sseerrnn**

### CODE REVIEW

**Comment by pol-alones** [comment]
I think you can wait to implement both swagger and regist in the same PR, according to task in JIRA (DEMO-47). Also don't forget to change the branch name to DEMO-47.

**Review by pol-alones — APPROVED** [review]
GJ

**Comment by pol-alones** [comment]
Btw, we should name the branch according to task in JIRA so we can track our progress. Also use the commit message convention that we have already decided next time.

**Review by karnjj — APPROVED** [review]
LGTM

**Review by NonKhuna — APPROVED** [review]
Good

**Pull request merged**
